# Update commit status in GitHub
updateCommitStatus: &UPDATE_COMMIT_STATUS
  onStart:
    - update_commit_status jfrog_cli_plugins_reg_git4 --context "$step_name"
  onComplete:
    - update_commit_status jfrog_cli_plugins_reg_git4 --context "$step_name"

commonConfiguration: &COMMON_CONFIGURATION
  inputResources:
    - name: jfrog_cli_plugins_reg_git4

resources:
  - name: buildJfrogCliPluginGit2
    type: GitRepo
    configuration:
      path: Or-Geva/jfrog-cli-plugins-reg
      gitProvider: or_cli_github
      buildOn:
        # Manually trigger only
        commit: false
      branches:
        # Only build on the master
        include: master
      files:
        include: ^plugins\/.+
  - name: jfrog_cli_plugins_reg_git4
    type: GitRepo
    configuration:
      path: Or-Geva/jfrog-cli-plugins-reg
      gitProvider: or_cli_github
      buildOn:
        commit: false
      branches:
        include: master

  - name: jfrog_or_core_cli
    type: GitRepo
    configuration:
      path: Or-Geva/abc
      gitProvider: or_cli_github
      buildOn:
        commit: false
        releaseCreate: true
      branches:
        include: master

pipelines:
  - name: or_plugin_release_new
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
    steps:
      - name: or_upgrade_plugin_on_core_release
        type: Bash
        configuration:
          inputResources:
            - name: jfrog_or_core_cli
          integrations:
            - name: ILAutomation2
            - name: JFrogCLIPluginsRegBot
            - name: or_token
        execution:
          onExecute:
            - git clone https://github.com/jfrog/jfrog-cli-plugins.git && jfrogCliPluginsPath=`pwd`/jfrog-cli-plugins
            - git clone https://github.com/jfrog/jfrog-cli-plugins-reg.git && cd jfrog-cli-plugins-reg/pipelinesScripts/validator
            - env -i PATH=$PATH issue_token=$int_JFrogCLIPluginsRegBot_token HOME=$HOME PWD=$PWD JAVA_HOME=$JAVA_HOME GRADLE_HOME=$GRADLE_HOME MAVEN_HOME=$MAVEN_HOME go run validator.go upgradejfrogplugins $jfrogCliPluginsPath
            - cd $jfrogCliPluginsPath
            # Override origin.
            - git remote set-url origin https://df6102abada5ca4cb312760722773359b965599b@github.com/jfrog/jfrog-cli-plugins.git && git fetch origin main && git checkout main
            # Check if new commits were added.
            - "[[ $(git log origin/main...main --oneline | wc -l) -eq 0 ]]"
            # Check if staged files contains none .mod or .sum files.
            - "[[ $(git diff --name-only --staged | grep -v -e .mod$ -e.sum$ | wc -l) -eq 0 ]]"
            # Check total number of staged files is not greater than  twice the number of directories (plugins).
            - "[[ $(git diff --name-only --staged | wc -l) -lt $(($(ls -l | grep ^d | wc -l)*2+1)) ]]"
            # Commit and push
            - git config user.email "eco-system+1@jfrog.com"
            - git config user.name "JFrog-CLI-Plugins-bot"
            - git commit -m "Updated plugins to the latest releases of jfrog-cli-core and jfrog-client-go"
            - git push origin main