name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,synchronize]
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Developer Terms and I hereby accept the terms') || github.event_name == 'pull_request_target'
        # Alpha Release
        uses: cla-assistant/github-action@13b2e0cfaba96607d535c9a30dddb2d36c260b45
        env:
          # Generated and maintained by github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # JFrog organization secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_SIGN_TOKEN }}
        with:
          path-to-signatures: 'signed_developer_terms.json'
          path-to-document: 'https://github.com/jfrog/jfrog-cli-plugins-reg/blob/master/DEVELOPERS_TERMS.md'
          remote-organization-name: 'jfrog'
          remote-repository-name: 'jfrog-signed-clas'
          # branch should not be protected
          branch: 'master'
          allowlist: bot*
          signed-commit-message: '$contributorName has accepted the Developer Terms in #$pullRequestNo'
          custom-notsigned-prcomment: 'Thank you for your submission, we really appreciate it. We ask that you accept our [JFrog CLI Plugins Developer Terms](https://github.com/jfrog/jfrog-cli-plugins-reg/blob/master/DEVELOPERS_TERMS.md) before we can accept your contribution. You can accept the Terms by just posting a Pull Request Comment same as the below format. Important: we recommend not to copy and paste this message, to avoid including unseen characters, which fail the message validation.'
          custom-pr-sign-comment: 'I have read the Developer Terms and I hereby accept the terms'
          custom-allsigned-prcomment: 'All Contributors have accepted the Developer Terms.'
